export const seoKeywords = [
  "Henrique Costa",
  "Web Developer",
  "Web Designer",
  "Portfolio",
  "Projects",
  "UI designer",
  "Frontend developer",
  "Backend developer",
  "Fullstack developer",
  "React developer",
  "Next.js developer",
  "Node.js developer",
  "NestJS developer",
  "MongoDB developer",
  "MERN stack developer",
  "Software developer",
  "Software engineer",
  "Web developer in Brazil",
  "Web developer in São Paulo",
];
